import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full w-full`}
      >
        <nav className="fixed top-0 w-full border-b border-gray-300 py-4 px-3 flex justify-end gap-3 bg-gray-200 shadow-xl">
          <Link
            href="/uploadPage"
            className="text-black underline underline-offset-3"
          >
            上傳PDF
          </Link>
          <Link
            href="/pdfViewerPage"
            className="text-black underline underline-offset-3"
          >
            圖片縮放頁
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
